install: ./.travis-lazarus/.travis.install.py

language: generic
sudo: required
dist: trusty

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_PKG=true  # Use the latest version from the default package manager
    - LAZ_VER=1.4.4 # Use specific (binary) release
    - LAZ_VER=1.8.2

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &

script:
  - lazbuild test/test_fpc.lpi         # Build project
  - test/test_fpc --all --format=plain # Run testsuite
