install: ./.travis-lazarus/.travis.install.py

language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_PKG=true  # Use the latest version from the default package manager
    - LAZ_VER=1.4.4 # Use specific (binary) release
    - LAZ_VER=1.8.2

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &

script:
  - lazbuild $LAZ_OPT test/testregexpr.lpi             # Build project
  - $LAZ_ENV test/testregexpr --all --format=plain # Run testsuite
