sudo: required
dist: trusty
install: ./.travis-lazarus/.travis.install.py

script:
  - lazbuild $LAZ_OPT test/tregexpr_test.lpi             # Build project
  - $LAZ_ENV test/bin/tregexpr_test --all --format=plain # Run testsuite
